(PIE-346) Add the status to the report_type
puppetlabs/puppetlabs-servicenow_reporting_integration pull request #41
Opened 2020-09-21 15:28 UTC by gregohardy

2020-09-21 16:53 UTC, gsparks approved these changes

2020-09-21 17:57 UTC, RandomNoun7 commented
This looks good and I've tested it works. Can we get some additional test cases added for `node_report_unchanged` and `node_report_failed`?

2020-09-23 17:18 UTC, RandomNoun7 requested changes

2020-09-23 17:18 UTC, RandomNoun7 commented on spec/unit/reports/servicenow/event_spec.rb
> +  it 'sends a node_report_unchanged' do
I think this line and line 78 are mixed up aren't they?

2020-09-23 19:46 UTC, RandomNoun7 approved these changes

2020-09-23 20:04 UTC, merged